### ISSUE TITLE
How is the preprocessed cell dictionary created? 

### ISSUE THREAD

**Issue by Akilax0** [ASU-VDA-Lab/ASP-DAC24-Tutorial#10]
In the gate sizing example, the following preprocessed cell dictionary is loaded.  How is this created? 

https://github.com/ASU-VDA-Lab/ASP-DAC24-Tutorial/blob/main/platforms/preprocessed_cell_dictionary.json

**Comment by bingyuew** [comment]
Just manual work, now openroad python api supports most functions.

**Comment by Akilax0** [comment]
I see. I do have some trouble though like reading input capacitance values or getting output pin from openroad API itself. (is there any specific documentation on the API other than https://openroad.readthedocs.io/en/latest/main/src/odb/README.html#python) 

Also what is n_sizes in the json. If it is just the number of sizes why is it only giving 3 for BUF when it has 6 sizes.

**Comment by bingyuew** [comment]
For input capacitance, you can refer to [this example](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/blob/58b8bdd0ca944eabf1c03830df932c5104ebce89/src/example/OpenROAD_example.py#L121) 
For output pin, you can refer to [this example](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/blob/58b8bdd0ca944eabf1c03830df932c5104ebce89/src/example/OpenROAD_example.py#L127)
Changed the n_size to 6 for BUF, thanks for the notice.

**Comment by bingyuew** [comment]
If the question is answered, please close the issue, thanks.
